import oclif from 'eslint-config-oclif';

export default [
  ...oclif,
  {
    ignores: ['@types', './lib', '**/*.js', '**/*.mjs']
  },
  {
    files: ['**/*.ts'],
    languageOptions: {
      parserOptions: {
        ecmaFeatures: {
          modules: true
        },
        ecmaVersion: 6,
        sourceType: 'module'
      }
    },
    rules: {
      '@stylistic/comma-dangle': 'warn',
      '@stylistic/arrow-parens': 'warn',
      '@stylistic/brace-style': 'warn',
      '@stylistic/comma-dangle': 'warn',
      '@stylistic/generator-star-spacing': 'warn',
      '@stylistic/indent': 'warn',
      '@stylistic/indent-binary-ops': 'warn',
      '@stylistic/function-paren-newline': 'warn',
      '@stylistic/lines-between-class-members': 'warn',
      '@stylistic/object-curly-newline': 'warn',
      '@stylistic/object-curly-spacing': 'warn',
      '@stylistic/operator-linebreak': 'warn',
      '@stylistic/padding-line-between-statements': 'warn',
      '@stylistic/quotes': 'warn',
      '@typescript-eslint/no-explicit-any': 'off',
      '@typescript-eslint/no-require-imports': 'warn',
      '@typescript-eslint/no-unused-expressions': 'warn',
      '@typescript-eslint/no-unused-vars': 'warn',
      'arrow-body-style': 'warn',
      camelcase: 'warn',
      'dot-notation': 'warn',
      'import/namespace': 'warn',
      'mocha/no-mocha-arrows': 'warn',
      'n/no-unpublished-import': 'warn',
      'n/no-unsupported-features/node-builtins': 'warn',
      'n/shebang': 'warn',
      'new-cap': 'warn',
      'no-await-in-loop': 'off',
      'no-bitwise': 'warn',
      'no-constructor-return': 'warn',
      'no-else-return': 'warn',
      'no-implicit-coercion': 'warn',
      'no-lone-blocks': 'warn',
      'no-multi-assign': 'warn',
      'no-promise-executor-return': 'warn',
      'no-prototype-builtins': 'warn',
      'no-restricted-globals': 'warn',
      'no-return-await': 'warn',
      'no-return-assign': 'warn',
      'no-undef': 'warn',
      'no-useless-return': 'warn',
      'no-void': 'warn',
      'node/no-missing-import': 'off',
      'object-shorthand': 'warn',
      'perfectionist/sort-classes': 'warn',
      'perfectionist/sort-enums': 'warn',
      'perfectionist/sort-imports': 'warn',
      'perfectionist/sort-interfaces': 'warn',
      'perfectionist/sort-intersection-types': 'warn',
      'perfectionist/sort-named-imports': 'warn',
      'perfectionist/sort-object-types': 'warn',
      'perfectionist/sort-objects': 'warn',
      'perfectionist/sort-switch-case': 'warn',
      'perfectionist/sort-union-types': 'warn',
      'prefer-arrow-callback': 'warn',
      'prefer-const': 'warn',
      'prefer-destructuring': 'warn',
      'unicorn/catch-error-name': 'warn',
      'unicorn/consistent-existence-index-check': 'warn',
      'unicorn/consistent-function-scoping': 'warn',
      'unicorn/escape-case': 'warn',
      'unicorn/explicit-length-check': 'warn',
      'unicorn/no-array-callback-reference': 'warn',
      'unicorn/no-array-for-each': 'off',
      'unicorn/no-array-push-push': 'warn',
      'unicorn/no-empty-file': 'warn',
      'unicorn/no-for-loop': 'warn',
      'unicorn/no-hex-escape': 'warn',
      'unicorn/no-negated-condition': 'warn',
      'unicorn/no-nested-ternary': 'warn',
      'unicorn/no-unreadable-array-destructuring': 'warn',
      'unicorn/no-useless-undefined': 'warn',
      'unicorn/prefer-array-find': 'warn',
      'unicorn/prefer-array-some': 'warn',
      'unicorn/prefer-dom-node-append': 'warn',
      'unicorn/prefer-event-target': 'warn',
      'unicorn/prefer-global-this': 'warn',
      'unicorn/prefer-math-trunc': 'warn',
      'unicorn/prefer-node-protocol': 'warn',
      'unicorn/prefer-number-properties': 'warn',
      'unicorn/prefer-optional-catch-binding': 'warn',
      'unicorn/prefer-query-selector': 'warn',
      'unicorn/prefer-regexp-test': 'warn',
      'unicorn/prefer-spread': 'warn',
      'unicorn/prefer-ternary': 'warn',
      'unicorn/switch-case-braces': 'warn'
    }
  }
];
